create table members (
    id bigint generated by default as identity primary key,
    email varchar(120) not null unique,
    name varchar(80) not null,
    phone_number varchar(30),
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table pregnancy_profiles (
    id bigint generated by default as identity primary key,
    member_id bigint not null unique references members(id),
    status varchar(20) not null,
    expected_birth_date date,
    child_birth_date date,
    pregnancy_week integer,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table consent_histories (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    consent_type varchar(40) not null,
    agreed boolean not null,
    agreed_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table care_contents (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    body text not null,
    category varchar(30) not null,
    target_pregnancy_week integer,
    published boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table products (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    category varchar(80) not null,
    price numeric(12, 2) not null,
    stock_quantity integer not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table cart_items (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    product_id bigint not null references products(id),
    quantity integer not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table orders (
    id bigint generated by default as identity primary key,
    order_number varchar(40) not null unique,
    member_id bigint not null references members(id),
    status varchar(20) not null,
    total_amount numeric(12, 2) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id),
    product_id bigint not null references products(id),
    quantity integer not null,
    unit_price numeric(12, 2) not null
);

create table payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references orders(id),
    amount numeric(12, 2) not null,
    payment_method varchar(40) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table deliveries (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references orders(id),
    receiver_name varchar(160) not null,
    receiver_phone varchar(30) not null,
    address varchar(300) not null,
    tracking_number varchar(80),
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table reviews (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    product_id bigint not null references products(id),
    rating integer not null,
    body varchar(1000) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table inquiries (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    product_id bigint references products(id),
    title varchar(160) not null,
    body varchar(1000) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table consultations (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    title varchar(160) not null,
    body varchar(1000) not null,
    status varchar(20) not null,
    internal_memo varchar(1000),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table coupons (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(120) not null,
    discount_amount numeric(12, 2) not null,
    starts_on date not null,
    ends_on date not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table notifications (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members(id),
    type varchar(30) not null,
    title varchar(160) not null,
    message varchar(500) not null,
    is_read boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table admin_users (
    id bigint generated by default as identity primary key,
    email varchar(120) not null unique,
    name varchar(80) not null,
    role varchar(30) not null,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    admin_user_id bigint not null references admin_users(id),
    target_member_id bigint references members(id),
    action varchar(40) not null,
    reason varchar(500) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

